### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by Pxlauzmi** [tempdata73/parking#1]

**Comment by Pxlauzmi** [comment]
I am currently working on a multi camera parking project based on Rasberry Pi, with yolo. Thanks a lot for your repository. Got much help.

**Comment by tempdata73** [comment]
I'm really happy you found this repo helpful, but yeah, it is no longer maintained as I moved on to other things. However if you find some bugs I'll gladly try and fix them. Good luck with your project :)
